env:
  browser: true
  es2020: true
  jest: true
extends:
  - airbnb-base
  - plugin:import/typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - jest.config.js
  - webpack.config.js
  - dist/*
rules:
  import/extensions:
    - error
    - ignorePackages
    - {
      js: never,
      mjs: never,
      jsx: never,
      ts: never,
      tsx: never,
      vue: never,
    }
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
